"""add session_attendance table

Revision ID: b7d4c2bf9a5e
Revises: 62e428fe9da6
Create Date: 2026-05-08 16:20:06.676888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b7d4c2bf9a5e'
down_revision = '62e428fe9da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('special_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('emoji', sa.String(), nullable=True),
    sa.Column('color', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('trophy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('unique', sa.Boolean(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('not_player_as_of', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=False)

    op.create_table('vtt',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('game',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('oneshot', 'campaign', 'videogame', name='game_type_enum'), nullable=False),
    sa.Column('length', sa.String(), nullable=False),
    sa.Column('gm_id', sa.String(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('vtt_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('restriction', sa.Enum('all', '16+', '18+', name='restriction_enum'), nullable=False),
    sa.Column('restriction_tags', sa.String(), nullable=True),
    sa.Column('party_size', sa.Integer(), nullable=False),
    sa.Column('party_selection', sa.Boolean(), nullable=False),
    sa.Column('create_voice', sa.Boolean(), nullable=False),
    sa.Column('experience', sa.Enum('all', 'beginners', 'seasoned', name='game_xp_enum'), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('session_length', sa.DECIMAL(precision=2, scale=1), nullable=False),
    sa.Column('frequency', sa.Enum('weekly', 'bi-weekly', 'monthly', 'other', name='game_frequency_enum'), nullable=True),
    sa.Column('characters', sa.Enum('with_gm', 'self', 'pregen', 'choice', name='game_char_enum'), nullable=True),
    sa.Column('classification', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ambience', postgresql.ARRAY(sa.Enum('chill', 'serious', 'comic', 'epic', name='game_ambience_enum')), nullable=True),
    sa.Column('complement', sa.Text(), nullable=True),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('voice_channel_id', sa.String(), nullable=True),
    sa.Column('msg_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'open', 'closed', 'archived', name='game_status_enum'), server_default='draft', nullable=False),
    sa.Column('special_event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['gm_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['special_event_id'], ['special_event.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.ForeignKeyConstraint(['vtt_id'], ['vtt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_slug'), ['slug'], unique=True)

    op.create_table('user_trophy',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('trophy_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trophy_id'], ['trophy.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'trophy_id')
    )
    op.create_table('game_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.Enum('create', 'edit', 'delete', 'create-session', 'edit-session', 'delete-session', 'register', 'unregister', 'alert', name='action_type_enum'), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_event', schema=None) as batch_op:
        batch_op.create_index('ix_gameevent_game', ['game_id'], unique=False)
        batch_op.create_index('ix_gameevent_timestamp', ['timestamp'], unique=False)

    op.create_table('game_players',
    sa.Column('game_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id'),
    sa.UniqueConstraint('game_id', 'player_id', name='uix_game_user')
    )
    op.create_table('game_session',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('location_type', sa.Enum('online', 'inperson', name='session_location_enum'), nullable=True),
    sa.Column('location_label', sa.String(), nullable=True),
    sa.Column('location_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_attendance',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('is_present', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['game_session.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'user_id', name='uix_session_user_attendance')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_attendance')
    op.drop_table('game_session')
    op.drop_table('game_players')
    with op.batch_alter_table('game_event', schema=None) as batch_op:
        batch_op.drop_index('ix_gameevent_timestamp')
        batch_op.drop_index('ix_gameevent_game')

    op.drop_table('game_event')
    op.drop_table('user_trophy')
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_slug'))

    op.drop_table('game')
    op.drop_table('vtt')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_name'))

    op.drop_table('user')
    op.drop_table('trophy')
    op.drop_table('system')
    op.drop_table('special_event')
    op.drop_table('channel')
    # ### end Alembic commands ###
